sudo: false
dist: trusty
env:
  - CXX=g++-4.8
  global:
    - ENCRYPTION_LABEL: "e75cc21342ac"
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_script:
  - npm i -g @unumux/ux-cli
after_success:
  - ./deploy.sh
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"