sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
after_success:
  - ./deploy.sh
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"